### ISSUE TITLE
Ⅰcannot__get_W

### ISSUE THREAD

**Issue by Keima623** [marijavella/hs-sr-tvtv#2]
get_W()# download data from Google drive
I can not get the data from it (Max retries exceeded with url: /u/0/uc?id=1bf6kWyAgf1JSTy25xwoR9qDLWG-UQtu7&export=download (Caused by ProxyError('Cannot connect to proxy.')
https://drive.google.com/u/0/uc?id=1bf6kWyAgf1JSTy25xwoR9qDLWG-UQtu7&export=download
https://drive.google.com/u/0/uc?id=1Jfr16RWW7BiukLiyzqOEqO8A9TCLujjG&export=download
https://drive.google.com/u/0/uc?id=15vTwIRimGoUxaE9JBGhHCTvI6EglRoYq&export=download
can you give the data in it please

**Comment by marijavella** [comment]
Hi, 

Thanks for flagging the issue. The Google Drive links and the `gdown` package requirements have been updated. To successfully run the code gdown==4.6.4 is now required.

**Comment by Keima623** [comment]
Thank you for your prompt reply, which really helped me a lot！
